base_url: "https://reder-test-o5k8.onrender.com"

disaster_types:
  - glof
  - flood
  - earthquake
  - mudslide
  - mudflow
  - avalanche
  - landslide
  - storm
  - volcano
  - cyclone
  - typhoon
  - tornado
